name: 'Deploy Async Request Reply Sample'

env:
    DOTNET_VERSION: '8.0.x'


on:
    workflow_dispatch:

jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - name: Run Bicep linter
        run: az bicep build --file ./async-request-reply/infra/main.bicep

   